[general]
    # This path will contain all the pickles that track the age of threat
    # intel, and when feeds were last checked.  It can be emptied to reset the
    # state.
    state_dir = "./state"

    # Location of log files
    log_dir = "./log"

[intelligence]
    # How long, from the timestamp the intel was discovered, should the
    # resulting detection pattern remain valid?
    valid_for_days = 30

    # How often should feed sources be checked?
    frequency_minutes = 15

# Each of these tables defines a named source
[source.taxii_source_demo]
    # What type of source to define.  Currently this is the only valid type.
    type = "taxii21"

    # Discovery URL for the TAXII 2.1 source
    url = "XXXXXXXXXXXXXX"

    # Credentials for the source
    username = "XXXXXXXXXXXXXXXXXX"
    password = "XXXXXXXXXXXXXXXXXX"

# Each of these tables defines a named destination
[destination.crowdstrike_detect_low]
    # Valid values are "crowdstrike" and "edl"
    type = "crowdstrike"

    # URL to the falcon tenant
    url = "https://api.us-2.crowdstrike.com"

    # The severity of detections generated by IoCs sent to this destination
    # Known valid values are informational, low, medium, high, and critical
    severity = "low"

    # What action to take on detection
    # Known valid values are block and detect
    action = "detect"

    # Credentials for the destination
    client_id = "XXXXXXXXXXXXXXXXXXXXX"
    client_secret = "XXXXXXXXXXXXXXXXXXX"

# An example of a more severe destination
[destination.crowdstrike_block_high]
    type = "crowdstrike"
    url = "https://api.us-2.crowdstrike.com"
    severity = "high"
    action = "block"
    client_id = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
    client_secret = "XXXXXXXXXXXXXXXXXXXXXXX"

# Configure an EDL destination for Palo Alto
[destination.edl_demo]
    # Valid values are "crowdstrike" and "edl"
    type = "edl"

    # Path to place EDL files
    output_dir = "./output"

    # File names for the managed lists
    ip = "ips.txt"
    domain = "domains.txt"
    url = "urls.txt"

# Each of these tables defines a copy job from a source to one or more
# destinations
[connection.demo_taxii2]
    # Which of the above source tables to copy from
    source = "taxii_source_demo"

    # Which of the above destination tables to copy to
    destinations = ["crowdstrike_detect_low", "edl_demo"]

    # The name of the collection on the source to copy.  These are defined by
    # the remote source
    collection = "ioc_feed"

[connection.demo_taxii1]
    # Which of the above source tables to copy from
    source = "taxii_source_demo"

    # Which of the above destination tables to copy to
    destinations = ["crowdstrike_detect_low", "edl_demo"]

    # The name of the collection on the source to copy.  These are defined by
    # the remote source
    collection = "demo_taxii1"